name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Clean install & build
        run: |
          cd knowledge-nuggets
          rm -rf node_modules package-lock.json dist
          npm install
          npm run build

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      

    
      - name: Install dependencies
        run: |
          cd knowledge-nuggets
          npm ci
    
      - name: Build
        run: |
          cd knowledge-nuggets
          npm run build
    
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./knowledge-nuggets/dist
